version: '3.5'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile-dev
    container_name: react-k8s-app
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
  tests:
    build:
      context: .
      dockerfile: Dockerfile-dev
    container_name: react-k8s-app-tests
    volumes:
      - /app/node_modules
      - .:/app
    command: [ "npm","run","test" ]